import pytest
import shutil
import os
from fastapi.testclient import TestClient
from backend.main import app
from backend.core.configs import settings
# from backend.services.script_service import script_service # Assuming script_service might also be risky if it depends on repo?
from backend.services.video_service import video_service

# Test data isolation
TEST_DATA_DIR = os.path.join(settings.STORAGE_DIR, "data_test")

# Global Mock Storage
mock_storage_global = {}

@pytest.fixture(scope="session", autouse=True)
def setup_test_env():
    # Replace the client with an AsyncMock that behaves like a real client for ALL tests
    from unittest.mock import AsyncMock, MagicMock
    mock_client = AsyncMock()
    
    # Generic side effect that returns valid JSON based on input
    def create_mock_response(content):
        m = MagicMock()
        m.choices = [MagicMock(message=MagicMock(content=content))]
        return m
    
    async def side_effect(*args, **kwargs):
        msgs = kwargs.get("messages", [])
        last_content = msgs[-1]["content"] if msgs else ""
        
        # Checking for trigger keywords sent by service
        if "TEST INIT" in last_content:
             return create_mock_response('{"visual_style": "Test", "characters": []}')
        if "TEST CHAPTERS" in last_content:
             return create_mock_response('{"chapters": [{"order": 1, "title": "C1", "description": "D1"}]}')
        if "TEST SUBCHAPTERS" in last_content:
             return create_mock_response('{"subchapters": [{"order": 1, "title": "S1", "description": "D1"}]}')
        if "TEST SCENES" in last_content:
             return create_mock_response('{"scenes": [{"id": 1, "order": 1, "duration_seconds": 10, "narration_content": "N", "character_name": "C", "voice_type": "V", "visual_description": "V", "image_prompt": "I", "video_prompt": "V", "audio_prompt": "A"}]}')
        return create_mock_response('{}')

    mock_client.chat.completions.create.side_effect = side_effect
    video_service.client = mock_client
    
    # Force Mock Prompts for Tests (Required since defaults removed)
    from backend.core.configs import settings
    settings.PROMPT_INIT_TEMPLATE = "TEST INIT {topic} {duration}"
    settings.PROMPT_CHAPTERS_TEMPLATE = "TEST CHAPTERS {language}"
    settings.PROMPT_SUBCHAPTERS_TEMPLATE = "TEST SUBCHAPTERS {chapter_order} {chapter_title}"
    settings.PROMPT_SCENES_TEMPLATE = "TEST SCENES {subchapter_title}"

    # --- Mock Datastore ---
    from unittest.mock import MagicMock, patch
    
    class MockKey:
        def __init__(self, kind, id_or_name=None):
             self._kind = kind
             self._id = None
             self._name = None
             
             if isinstance(id_or_name, str):
                 self._name = id_or_name
             elif isinstance(id_or_name, int):
                 self._id = id_or_name
             elif id_or_name is None:
                 # Auto ID
                 self._id = len(mock_storage_global) + 1
             
             self._path = None
        
        @property
        def id(self):
            return self._id

        @property
        def name(self):
            return self._name
        
        @property
        def kind(self):
            return self._kind

    class MockEntity(dict):
        def __init__(self, key):
            super().__init__()
            self.key = key
            self.exclude_from_indexes = []

    class MockQuery:
        def __init__(self, client, kind):
            self.client = client
            self.kind = kind
            self.order = []
        
        def fetch(self, limit=None):
            results = []
            for key_tuple, ent in mock_storage_global.items():
                if key_tuple[0] == self.kind:
                    results.append(ent)
            results.sort(key=lambda x: x.get("created_at", ""), reverse=True)
            return results[:limit] if limit else results

    class MockDatastoreClient:
        def __init__(self, project="test"):
            self.project = project
        
        def key(self, kind, id=None):
            return MockKey(kind, id)
        
        def get(self, key):
            k = (key.kind, key.id)
            return mock_storage_global.get(k)
        
        def put(self, entity):
            # If key ID was auto-generated by MockKey logic but strictly speaking
            # Entity logic might separate key generation.
            # Simulating:
            k = (entity.key.kind, entity.key.id)
            mock_storage_global[k] = entity
            
        def query(self, kind):
            return MockQuery(self, kind)

    # Patch the get_datastore_client to return our Mock
    mock_ds_client = MockDatastoreClient()
    
    with patch("backend.repositories.video_repository.get_datastore_client", return_value=mock_ds_client), \
         patch("backend.repositories.user_repository.get_datastore_client", return_value=mock_ds_client):
        # We also need to patch the singleton in datastore_client if used directly?
        # The repo imports it. `from backend.core.datastore_client import get_datastore_client`
        # The patch above targets where it is USED.
        
        
        yield
        
    # Cleanup after all tests in the session
    if os.path.exists(TEST_DATA_DIR):
        shutil.rmtree(TEST_DATA_DIR)
    
    mock_storage_global.clear() # Clear mock storage after all tests

@pytest.fixture(scope="function", autouse=True)
def clean_data_folder():
    if os.path.exists(TEST_DATA_DIR):
         shutil.rmtree(TEST_DATA_DIR)
    os.makedirs(TEST_DATA_DIR, exist_ok=True)

@pytest.fixture(scope="function", autouse=True)
def clean_datastore():
    # Clear mock storage between tests
    mock_storage_global.clear()

@pytest.fixture(scope="function")
def client():
    # Override Auth Dependency
    from backend.api.deps import get_current_user
    from backend.models.user import UserModel
    
    # Mock User
    mock_user = UserModel(
        email="test@test.com",
        hashed_password="mock",
        full_name="Test User",
        is_active=True,
        groups=["test"]
    )
    
    app.dependency_overrides[get_current_user] = lambda: mock_user
    
    with TestClient(app) as c:
        yield c
    
    app.dependency_overrides = {}
